@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

POST {{baseUrl}}/accounts/member
Content-Type: application/json

{
    "name": "Daniel Vieira",
    "email": "dani@gmail.com",
    "password": "123456"
}
###

POST {{baseUrl}}/accounts/admin
Content-Type: application/json

{
    "name": "Daniel Vieira",
    "email": "daniadmin@gmail.com",

    "password": "123456"
}

### 

# @name authenticate

POST {{baseUrl}}/sessions/admin
Content-Type: application/json

{
    "email": "daniadmin@gmail.com",
    "password": "123456"
}

### 

POST {{baseUrl}}/sessions/member
Content-Type: application/json

{
    "email": "dani@gmail.com",
    "password": "123456"
}

### 
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Test",
    "description":"description",
    "repositoryLink": "link",
    "attachmentsIds": ["1","2"]
}

### 
POST {{baseUrl}}/projects/6252f5d8-49cf-44f5-ae2f-7b39cc8aa242/feedbacks
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Feedback-test",
    "grade": "3",
    "comment": "New comment"
}

### 
POST {{baseUrl}}/feedbacks/35373c22-5b16-4773-afa4-1baa0ccc5a9d/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "content": "Content"
}

###

GET {{baseUrl}}/projects?=page


###

GET {{baseUrl}}/projects/23667012-07e0-4e81-9ac7-cae56490f487